# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget cudpp cudpp_hash)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target cudpp
add_library(cudpp STATIC IMPORTED)

# Create imported target cudpp_hash
add_library(cudpp_hash STATIC IMPORTED)

# Import target "cudpp" for configuration "Debug"
set_property(TARGET cudpp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(cudpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/Win32/cudart_static.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/gaomi/Desktop/cudpp-test/lib/cudpp32d.lib"
  )

# Import target "cudpp_hash" for configuration "Debug"
set_property(TARGET cudpp_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(cudpp_hash PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/Win32/cudart_static.lib;cudpp"
  IMPORTED_LOCATION_DEBUG "C:/Users/gaomi/Desktop/cudpp-test/lib/cudpp_hash32d.lib"
  )

# Import target "cudpp" for configuration "Release"
set_property(TARGET cudpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cudpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/Win32/cudart_static.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/gaomi/Desktop/cudpp-test/lib/cudpp32.lib"
  )

# Import target "cudpp_hash" for configuration "Release"
set_property(TARGET cudpp_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cudpp_hash PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/Win32/cudart_static.lib;cudpp"
  IMPORTED_LOCATION_RELEASE "C:/Users/gaomi/Desktop/cudpp-test/lib/cudpp_hash32.lib"
  )

# Import target "cudpp" for configuration "MinSizeRel"
set_property(TARGET cudpp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(cudpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/Win32/cudart_static.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/gaomi/Desktop/cudpp-test/lib/cudpp32.lib"
  )

# Import target "cudpp_hash" for configuration "MinSizeRel"
set_property(TARGET cudpp_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(cudpp_hash PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/Win32/cudart_static.lib;cudpp"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/gaomi/Desktop/cudpp-test/lib/cudpp_hash32.lib"
  )

# Import target "cudpp" for configuration "RelWithDebInfo"
set_property(TARGET cudpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(cudpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/Win32/cudart_static.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/gaomi/Desktop/cudpp-test/lib/cudpp32.lib"
  )

# Import target "cudpp_hash" for configuration "RelWithDebInfo"
set_property(TARGET cudpp_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(cudpp_hash PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/Win32/cudart_static.lib;cudpp"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/gaomi/Desktop/cudpp-test/lib/cudpp_hash32.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
